# Generated by Django 4.1 on 2022-08-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_amount_status_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amount_status",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=8, null=True
            ),
        ),
    ]
