# Generated by Django 4.1 on 2022-08-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Store_Name", models.CharField(max_length=200)),
                ("Contact_No", models.IntegerField()),
                ("GST_IN", models.CharField(blank=True, max_length=100, null=True)),
                ("PAN_CARD", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={"verbose_name_plural": "Customer",},
        ),
        migrations.CreateModel(
            name="Amount_Received",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                (
                    "Amount_Received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "Store_Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.customer",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Amount_Received",},
        ),
        migrations.CreateModel(
            name="Amount_Lended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Amount_Lended", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Store_Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.customer",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Amount_Lended",},
        ),
    ]
