# Generated by Django 4.1 on 2022-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_amount_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amount_status",
            name="amount",
            field=models.DecimalField(blank=0, decimal_places=3, max_digits=8, null=0),
        ),
    ]
