# Generated by Django 4.1 on 2022-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_amount_lended_amount_lended_amount_lended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amount_status",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
