# Generated by Django 4.1 on 2022-08-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_lending_price_alter_item_mrp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="HSN_no", new_name="hsn_no",
        ),
        migrations.RenameField(
            model_name="item", old_name="Lending_Price", new_name="lending_price",
        ),
        migrations.RenameField(model_name="item", old_name="MRP", new_name="mrp",),
    ]
