# Generated by Django 4.1 on 2022-08-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=400)),
                ("HSN_no", models.IntegerField()),
                ("MRP", models.IntegerField()),
                ("box_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("s_gst", models.DecimalField(decimal_places=2, max_digits=5)),
                ("c_gst", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scheme", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
