# Generated by Django 4.1 on 2022-08-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="item_name", new_name="itemname",
        ),
    ]
