# Generated by Django 4.1 on 2022-08-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_rename_item_name_item_itemname"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Lending_Price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="item",
            name="MRP",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
