# Generated by Django 4.1 on 2022-08-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_no", models.IntegerField()),
                ("items", models.CharField(max_length=400)),
                ("boxes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_no", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("boxes", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stocks.stocks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_no", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("boxes", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stocks.stocks",
                    ),
                ),
            ],
        ),
    ]
