# Generated by Django 4.1 on 2022-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_alter_purchase_items_alter_sale_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
