# Generated by Django 4.1 on 2022-08-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_remove_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
