# Generated by Django 4.1 on 2022-08-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase", name="date", field=models.DateField(),
        ),
    ]
