# Generated by Django 4.1 on 2022-08-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0013_stock"),
    ]

    operations = [
        migrations.RemoveField(model_name="stock", name="item",),
        migrations.AddField(
            model_name="stock",
            name="items",
            field=models.CharField(default="", max_length=200),
        ),
    ]
