# Generated by Django 4.1 on 2022-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0015_remove_stock_boxes_remove_stock_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="stock", name="items",),
        migrations.AddField(
            model_name="stock", name="box", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stock",
            name="item",
            field=models.CharField(default="-", max_length=100),
        ),
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
