# Generated by Django 4.1 on 2022-08-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_alter_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
