# Generated by Django 4.1 on 2022-08-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0010_alter_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale", name="date", field=models.DateField(),
        ),
    ]
