# Generated by Django 4.1 on 2022-08-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0011_alter_sale_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale", old_name="boxes", new_name="boxes_out",
        ),
        migrations.RenameField(
            model_name="sale", old_name="s_no", new_name="boxes_return",
        ),
        migrations.RemoveField(model_name="purchase", name="s_no",),
        migrations.AlterField(
            model_name="purchase",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.DeleteModel(name="Stocks",),
    ]
