# Generated by Django 4.1 on 2022-08-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0014_remove_stock_item_stock_items"),
    ]

    operations = [
        migrations.RemoveField(model_name="stock", name="boxes",),
        migrations.RemoveField(model_name="stock", name="price",),
    ]
