# Generated by Django 4.1 on 2022-08-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0018_alter_stock_box_alter_stock_price"),
    ]

    operations = [
        migrations.RenameField(model_name="stock", old_name="name", new_name="items",),
    ]
