# Generated by Django 4.1 on 2022-08-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_lending_price_alter_item_mrp"),
        ("stocks", "0019_rename_name_stock_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="items.item"
            ),
        ),
    ]
